// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for MultiQuizExerciseType.
const (
	MultiQuizExerciseTypeMultiQuiz MultiQuizExerciseType = "multi-quiz"
)

// Valid indicates whether the value is a known member of the MultiQuizExerciseType enum.
func (e MultiQuizExerciseType) Valid() bool {
	switch e {
	case MultiQuizExerciseTypeMultiQuiz:
		return true
	default:
		return false
	}
}

// Defines values for MultiQuizExerciseResultType.
const (
	MultiQuizExerciseResultTypeMultiQuiz MultiQuizExerciseResultType = "multi-quiz"
)

// Valid indicates whether the value is a known member of the MultiQuizExerciseResultType enum.
func (e MultiQuizExerciseResultType) Valid() bool {
	switch e {
	case MultiQuizExerciseResultTypeMultiQuiz:
		return true
	default:
		return false
	}
}

// Defines values for MultiQuizQuestionSubmissionType.
const (
	MultiQuizQuestionSubmissionTypeMultiQuiz MultiQuizQuestionSubmissionType = "multi-quiz"
)

// Valid indicates whether the value is a known member of the MultiQuizQuestionSubmissionType enum.
func (e MultiQuizQuestionSubmissionType) Valid() bool {
	switch e {
	case MultiQuizQuestionSubmissionTypeMultiQuiz:
		return true
	default:
		return false
	}
}

// Defines values for MultiQuizSubmissionType.
const (
	MultiQuizSubmissionTypeMultiQuiz MultiQuizSubmissionType = "multi-quiz"
)

// Valid indicates whether the value is a known member of the MultiQuizSubmissionType enum.
func (e MultiQuizSubmissionType) Valid() bool {
	switch e {
	case MultiQuizSubmissionTypeMultiQuiz:
		return true
	default:
		return false
	}
}

// Defines values for PracticeStatus.
const (
	PracticeStatusCompleted  PracticeStatus = "completed"
	PracticeStatusInProgress PracticeStatus = "in_progress"
	PracticeStatusPending    PracticeStatus = "pending"
)

// Valid indicates whether the value is a known member of the PracticeStatus enum.
func (e PracticeStatus) Valid() bool {
	switch e {
	case PracticeStatusCompleted:
		return true
	case PracticeStatusInProgress:
		return true
	case PracticeStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for ListPracticesParamsStatus.
const (
	ListPracticesParamsStatusCompleted  ListPracticesParamsStatus = "completed"
	ListPracticesParamsStatusInProgress ListPracticesParamsStatus = "in_progress"
	ListPracticesParamsStatusPending    ListPracticesParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the ListPracticesParamsStatus enum.
func (e ListPracticesParamsStatus) Valid() bool {
	switch e {
	case ListPracticesParamsStatusCompleted:
		return true
	case ListPracticesParamsStatusInProgress:
		return true
	case ListPracticesParamsStatusPending:
		return true
	default:
		return false
	}
}

// CreateNoteRequest defines model for CreateNoteRequest.
type CreateNoteRequest struct {
	Content string `json:"content"`
	Title   string `json:"title"`
}

// CreatePracticeRequest defines model for CreatePracticeRequest.
type CreatePracticeRequest struct {
	NoteId openapi_types.UUID `json:"noteId"`
}

// CreatePracticeResponse defines model for CreatePracticeResponse.
type CreatePracticeResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// Exercise defines model for Exercise.
type Exercise struct {
	union json.RawMessage
}

// ListNotesResponse defines model for ListNotesResponse.
type ListNotesResponse struct {
	Items []Note `json:"items"`
	Limit int    `json:"limit"`
	Page  int    `json:"page"`
	Total int    `json:"total"`
}

// ListPracticesResponse defines model for ListPracticesResponse.
type ListPracticesResponse struct {
	Items []Practice `json:"items"`
	Total int        `json:"total"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Username string `json:"username"`
}

// MultiQuizExercise defines model for MultiQuizExercise.
type MultiQuizExercise struct {
	Id        openapi_types.UUID    `json:"id"`
	Questions []MultiQuizQuestion   `json:"questions"`
	Type      MultiQuizExerciseType `json:"type"`
}

// MultiQuizExerciseType defines model for MultiQuizExercise.Type.
type MultiQuizExerciseType string

// MultiQuizExerciseResult defines model for MultiQuizExerciseResult.
type MultiQuizExerciseResult struct {
	Correct          bool                        `json:"correct"`
	QuestionId       openapi_types.UUID          `json:"questionId"`
	SelectedOptionId openapi_types.UUID          `json:"selectedOptionId"`
	Type             MultiQuizExerciseResultType `json:"type"`
}

// MultiQuizExerciseResultType defines model for MultiQuizExerciseResult.Type.
type MultiQuizExerciseResultType string

// MultiQuizQuestion defines model for MultiQuizQuestion.
type MultiQuizQuestion struct {
	Id      openapi_types.UUID `json:"id"`
	Options []struct {
		Id   openapi_types.UUID `json:"id"`
		Text string             `json:"text"`
	} `json:"options"`
	Question   string `json:"question"`
	Submission *struct {
		Correct          bool                            `json:"correct"`
		SelectedOptionId openapi_types.UUID              `json:"selectedOptionId"`
		Type             MultiQuizQuestionSubmissionType `json:"type"`
	} `json:"submission,omitempty"`
}

// MultiQuizQuestionSubmissionType defines model for MultiQuizQuestion.Submission.Type.
type MultiQuizQuestionSubmissionType string

// MultiQuizSubmission defines model for MultiQuizSubmission.
type MultiQuizSubmission struct {
	QuestionId       openapi_types.UUID      `json:"questionId"`
	SelectedOptionId openapi_types.UUID      `json:"selectedOptionId"`
	Type             MultiQuizSubmissionType `json:"type"`
}

// MultiQuizSubmissionType defines model for MultiQuizSubmission.Type.
type MultiQuizSubmissionType string

// Note defines model for Note.
type Note struct {
	// Content Note body in Markdown format
	Content   string             `json:"content"`
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Title     string             `json:"title"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// Practice defines model for Practice.
type Practice struct {
	CompletedAt *time.Time         `json:"completedAt,omitempty"`
	CreatedAt   time.Time          `json:"createdAt"`
	Exercises   []Exercise         `json:"exercises"`
	Id          openapi_types.UUID `json:"id"`
	NoteId      openapi_types.UUID `json:"noteId"`
	Status      PracticeStatus     `json:"status"`
}

// PracticeStatus defines model for Practice.Status.
type PracticeStatus string

// SubmitExerciseRequest defines model for SubmitExerciseRequest.
type SubmitExerciseRequest struct {
	union json.RawMessage
}

// SubmitExerciseResponse defines model for SubmitExerciseResponse.
type SubmitExerciseResponse struct {
	union json.RawMessage
}

// UpdateNoteRequest defines model for UpdateNoteRequest.
type UpdateNoteRequest struct {
	Content *string `json:"content,omitempty"`
	Title   *string `json:"title,omitempty"`
}

// Conflict defines model for Conflict.
type Conflict = CreatePracticeResponse

// ListNotesParams defines parameters for ListNotes.
type ListNotesParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListPracticesParams defines parameters for ListPractices.
type ListPracticesParams struct {
	NoteId *openapi_types.UUID          `form:"noteId,omitempty" json:"noteId,omitempty"`
	Status *[]ListPracticesParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int                         `form:"limit,omitempty" json:"limit,omitempty"`
	Page   *int                         `form:"page,omitempty" json:"page,omitempty"`
}

// ListPracticesParamsStatus defines parameters for ListPractices.
type ListPracticesParamsStatus string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateNoteJSONRequestBody defines body for CreateNote for application/json ContentType.
type CreateNoteJSONRequestBody = CreateNoteRequest

// UpdateNoteJSONRequestBody defines body for UpdateNote for application/json ContentType.
type UpdateNoteJSONRequestBody = UpdateNoteRequest

// CreatePracticeJSONRequestBody defines body for CreatePractice for application/json ContentType.
type CreatePracticeJSONRequestBody = CreatePracticeRequest

// SubmitExerciseJSONRequestBody defines body for SubmitExercise for application/json ContentType.
type SubmitExerciseJSONRequestBody = SubmitExerciseRequest

// AsMultiQuizExercise returns the union data inside the Exercise as a MultiQuizExercise
func (t Exercise) AsMultiQuizExercise() (MultiQuizExercise, error) {
	var body MultiQuizExercise
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMultiQuizExercise overwrites any union data inside the Exercise as the provided MultiQuizExercise
func (t *Exercise) FromMultiQuizExercise(v MultiQuizExercise) error {
	v.Type = "multi-quiz"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMultiQuizExercise performs a merge with any union data inside the Exercise, using the provided MultiQuizExercise
func (t *Exercise) MergeMultiQuizExercise(v MultiQuizExercise) error {
	v.Type = "multi-quiz"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Exercise) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Exercise) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "multi-quiz":
		return t.AsMultiQuizExercise()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Exercise) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Exercise) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMultiQuizSubmission returns the union data inside the SubmitExerciseRequest as a MultiQuizSubmission
func (t SubmitExerciseRequest) AsMultiQuizSubmission() (MultiQuizSubmission, error) {
	var body MultiQuizSubmission
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMultiQuizSubmission overwrites any union data inside the SubmitExerciseRequest as the provided MultiQuizSubmission
func (t *SubmitExerciseRequest) FromMultiQuizSubmission(v MultiQuizSubmission) error {
	v.Type = "multi-quiz"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMultiQuizSubmission performs a merge with any union data inside the SubmitExerciseRequest, using the provided MultiQuizSubmission
func (t *SubmitExerciseRequest) MergeMultiQuizSubmission(v MultiQuizSubmission) error {
	v.Type = "multi-quiz"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SubmitExerciseRequest) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SubmitExerciseRequest) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "multi-quiz":
		return t.AsMultiQuizSubmission()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SubmitExerciseRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SubmitExerciseRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMultiQuizExerciseResult returns the union data inside the SubmitExerciseResponse as a MultiQuizExerciseResult
func (t SubmitExerciseResponse) AsMultiQuizExerciseResult() (MultiQuizExerciseResult, error) {
	var body MultiQuizExerciseResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMultiQuizExerciseResult overwrites any union data inside the SubmitExerciseResponse as the provided MultiQuizExerciseResult
func (t *SubmitExerciseResponse) FromMultiQuizExerciseResult(v MultiQuizExerciseResult) error {
	v.Type = "multi-quiz"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMultiQuizExerciseResult performs a merge with any union data inside the SubmitExerciseResponse, using the provided MultiQuizExerciseResult
func (t *SubmitExerciseResponse) MergeMultiQuizExerciseResult(v MultiQuizExerciseResult) error {
	v.Type = "multi-quiz"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SubmitExerciseResponse) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SubmitExerciseResponse) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "multi-quiz":
		return t.AsMultiQuizExerciseResult()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SubmitExerciseResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SubmitExerciseResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)

	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)

	// (GET /auth/me)
	GetMe(w http.ResponseWriter, r *http.Request)

	// (POST /concepts/{id}/archive)
	ArchiveConcept(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /concepts/{id}/restore)
	RestoreConcept(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /notes)
	ListNotes(w http.ResponseWriter, r *http.Request, params ListNotesParams)

	// (POST /notes)
	CreateNote(w http.ResponseWriter, r *http.Request)

	// (DELETE /notes/{id})
	DeleteNote(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /notes/{id})
	GetNote(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PATCH /notes/{id})
	UpdateNote(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /practices)
	ListPractices(w http.ResponseWriter, r *http.Request, params ListPracticesParams)

	// (POST /practices)
	CreatePractice(w http.ResponseWriter, r *http.Request)

	// (GET /practices/{id})
	GetPractice(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PATCH /practices/{id}/exercises/{exerciseId})
	SubmitExercise(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, exerciseId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /auth/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /concepts/{id}/archive)
func (_ Unimplemented) ArchiveConcept(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /concepts/{id}/restore)
func (_ Unimplemented) RestoreConcept(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /notes)
func (_ Unimplemented) ListNotes(w http.ResponseWriter, r *http.Request, params ListNotesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /notes)
func (_ Unimplemented) CreateNote(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /notes/{id})
func (_ Unimplemented) DeleteNote(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /notes/{id})
func (_ Unimplemented) GetNote(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /notes/{id})
func (_ Unimplemented) UpdateNote(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /practices)
func (_ Unimplemented) ListPractices(w http.ResponseWriter, r *http.Request, params ListPracticesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /practices)
func (_ Unimplemented) CreatePractice(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /practices/{id})
func (_ Unimplemented) GetPractice(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /practices/{id}/exercises/{exerciseId})
func (_ Unimplemented) SubmitExercise(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, exerciseId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ArchiveConcept operation middleware
func (siw *ServerInterfaceWrapper) ArchiveConcept(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ArchiveConcept(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreConcept operation middleware
func (siw *ServerInterfaceWrapper) RestoreConcept(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreConcept(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNotes operation middleware
func (siw *ServerInterfaceWrapper) ListNotes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNotesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNotes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNote operation middleware
func (siw *ServerInterfaceWrapper) CreateNote(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNote(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNote operation middleware
func (siw *ServerInterfaceWrapper) DeleteNote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNote(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNote operation middleware
func (siw *ServerInterfaceWrapper) GetNote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNote(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNote operation middleware
func (siw *ServerInterfaceWrapper) UpdateNote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNote(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPractices operation middleware
func (siw *ServerInterfaceWrapper) ListPractices(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPracticesParams

	// ------------- Optional query parameter "noteId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "noteId", r.URL.Query(), &params.NoteId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "noteId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "noteId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPractices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePractice operation middleware
func (siw *ServerInterfaceWrapper) CreatePractice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePractice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPractice operation middleware
func (siw *ServerInterfaceWrapper) GetPractice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPractice(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitExercise operation middleware
func (siw *ServerInterfaceWrapper) SubmitExercise(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "exerciseId" -------------
	var exerciseId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "exerciseId", chi.URLParam(r, "exerciseId"), &exerciseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "exerciseId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitExercise(w, r, id, exerciseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/concepts/{id}/archive", wrapper.ArchiveConcept)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/concepts/{id}/restore", wrapper.RestoreConcept)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/notes", wrapper.ListNotes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/notes", wrapper.CreateNote)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/notes/{id}", wrapper.DeleteNote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/notes/{id}", wrapper.GetNote)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/notes/{id}", wrapper.UpdateNote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/practices", wrapper.ListPractices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/practices", wrapper.CreatePractice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/practices/{id}", wrapper.GetPractice)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/practices/{id}/exercises/{exerciseId}", wrapper.SubmitExercise)
	})

	return r
}

type BadRequestResponse struct {
}

type ConflictJSONResponse CreatePracticeResponse

type NotFoundResponse struct {
}

type UnauthorizedResponse struct {
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200Response struct {
}

func (response Login200Response) VisitLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Login401Response = UnauthorizedResponse

func (response Login401Response) VisitLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse MeResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401Response = UnauthorizedResponse

func (response GetMe401Response) VisitGetMeResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ArchiveConceptRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type ArchiveConceptResponseObject interface {
	VisitArchiveConceptResponse(w http.ResponseWriter) error
}

type ArchiveConcept204Response struct {
}

func (response ArchiveConcept204Response) VisitArchiveConceptResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ArchiveConcept401Response = UnauthorizedResponse

func (response ArchiveConcept401Response) VisitArchiveConceptResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ArchiveConcept404Response = NotFoundResponse

func (response ArchiveConcept404Response) VisitArchiveConceptResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type RestoreConceptRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type RestoreConceptResponseObject interface {
	VisitRestoreConceptResponse(w http.ResponseWriter) error
}

type RestoreConcept204Response struct {
}

func (response RestoreConcept204Response) VisitRestoreConceptResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RestoreConcept401Response = UnauthorizedResponse

func (response RestoreConcept401Response) VisitRestoreConceptResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type RestoreConcept404Response = NotFoundResponse

func (response RestoreConcept404Response) VisitRestoreConceptResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ListNotesRequestObject struct {
	Params ListNotesParams
}

type ListNotesResponseObject interface {
	VisitListNotesResponse(w http.ResponseWriter) error
}

type ListNotes200JSONResponse ListNotesResponse

func (response ListNotes200JSONResponse) VisitListNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListNotes401Response = UnauthorizedResponse

func (response ListNotes401Response) VisitListNotesResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type CreateNoteRequestObject struct {
	Body *CreateNoteJSONRequestBody
}

type CreateNoteResponseObject interface {
	VisitCreateNoteResponse(w http.ResponseWriter) error
}

type CreateNote201JSONResponse Note

func (response CreateNote201JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNote400Response = BadRequestResponse

func (response CreateNote400Response) VisitCreateNoteResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateNote401Response = UnauthorizedResponse

func (response CreateNote401Response) VisitCreateNoteResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type DeleteNoteRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteNoteResponseObject interface {
	VisitDeleteNoteResponse(w http.ResponseWriter) error
}

type DeleteNote204Response struct {
}

func (response DeleteNote204Response) VisitDeleteNoteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteNote401Response = UnauthorizedResponse

func (response DeleteNote401Response) VisitDeleteNoteResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type DeleteNote404Response = NotFoundResponse

func (response DeleteNote404Response) VisitDeleteNoteResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetNoteRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetNoteResponseObject interface {
	VisitGetNoteResponse(w http.ResponseWriter) error
}

type GetNote200JSONResponse Note

func (response GetNote200JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNote401Response = UnauthorizedResponse

func (response GetNote401Response) VisitGetNoteResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetNote404Response = NotFoundResponse

func (response GetNote404Response) VisitGetNoteResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateNoteRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateNoteJSONRequestBody
}

type UpdateNoteResponseObject interface {
	VisitUpdateNoteResponse(w http.ResponseWriter) error
}

type UpdateNote200JSONResponse Note

func (response UpdateNote200JSONResponse) VisitUpdateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateNote400Response = BadRequestResponse

func (response UpdateNote400Response) VisitUpdateNoteResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type UpdateNote401Response = UnauthorizedResponse

func (response UpdateNote401Response) VisitUpdateNoteResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type UpdateNote404Response = NotFoundResponse

func (response UpdateNote404Response) VisitUpdateNoteResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ListPracticesRequestObject struct {
	Params ListPracticesParams
}

type ListPracticesResponseObject interface {
	VisitListPracticesResponse(w http.ResponseWriter) error
}

type ListPractices200JSONResponse ListPracticesResponse

func (response ListPractices200JSONResponse) VisitListPracticesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPractices401Response = UnauthorizedResponse

func (response ListPractices401Response) VisitListPracticesResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type CreatePracticeRequestObject struct {
	Body *CreatePracticeJSONRequestBody
}

type CreatePracticeResponseObject interface {
	VisitCreatePracticeResponse(w http.ResponseWriter) error
}

type CreatePractice201JSONResponse CreatePracticeResponse

func (response CreatePractice201JSONResponse) VisitCreatePracticeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePractice400Response = BadRequestResponse

func (response CreatePractice400Response) VisitCreatePracticeResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreatePractice401Response = UnauthorizedResponse

func (response CreatePractice401Response) VisitCreatePracticeResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type CreatePractice409JSONResponse struct{ ConflictJSONResponse }

func (response CreatePractice409JSONResponse) VisitCreatePracticeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetPracticeRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetPracticeResponseObject interface {
	VisitGetPracticeResponse(w http.ResponseWriter) error
}

type GetPractice200JSONResponse Practice

func (response GetPractice200JSONResponse) VisitGetPracticeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPractice401Response = UnauthorizedResponse

func (response GetPractice401Response) VisitGetPracticeResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetPractice404Response = NotFoundResponse

func (response GetPractice404Response) VisitGetPracticeResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type SubmitExerciseRequestObject struct {
	Id         openapi_types.UUID `json:"id"`
	ExerciseId openapi_types.UUID `json:"exerciseId"`
	Body       *SubmitExerciseJSONRequestBody
}

type SubmitExerciseResponseObject interface {
	VisitSubmitExerciseResponse(w http.ResponseWriter) error
}

type SubmitExercise200JSONResponse SubmitExerciseResponse

func (t SubmitExercise200JSONResponse) MarshalJSON() ([]byte, error) {
	return SubmitExerciseResponse(t).MarshalJSON()
}

func (t *SubmitExercise200JSONResponse) UnmarshalJSON(b []byte) error {
	return (*SubmitExerciseResponse)(t).UnmarshalJSON(b)
}

func (response SubmitExercise200JSONResponse) VisitSubmitExerciseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitExercise400Response = BadRequestResponse

func (response SubmitExercise400Response) VisitSubmitExerciseResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type SubmitExercise401Response = UnauthorizedResponse

func (response SubmitExercise401Response) VisitSubmitExerciseResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type SubmitExercise404Response = NotFoundResponse

func (response SubmitExercise404Response) VisitSubmitExerciseResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type SubmitExercise409Response struct {
}

func (response SubmitExercise409Response) VisitSubmitExerciseResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)

	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)

	// (GET /auth/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)

	// (POST /concepts/{id}/archive)
	ArchiveConcept(ctx context.Context, request ArchiveConceptRequestObject) (ArchiveConceptResponseObject, error)

	// (POST /concepts/{id}/restore)
	RestoreConcept(ctx context.Context, request RestoreConceptRequestObject) (RestoreConceptResponseObject, error)

	// (GET /notes)
	ListNotes(ctx context.Context, request ListNotesRequestObject) (ListNotesResponseObject, error)

	// (POST /notes)
	CreateNote(ctx context.Context, request CreateNoteRequestObject) (CreateNoteResponseObject, error)

	// (DELETE /notes/{id})
	DeleteNote(ctx context.Context, request DeleteNoteRequestObject) (DeleteNoteResponseObject, error)

	// (GET /notes/{id})
	GetNote(ctx context.Context, request GetNoteRequestObject) (GetNoteResponseObject, error)

	// (PATCH /notes/{id})
	UpdateNote(ctx context.Context, request UpdateNoteRequestObject) (UpdateNoteResponseObject, error)

	// (GET /practices)
	ListPractices(ctx context.Context, request ListPracticesRequestObject) (ListPracticesResponseObject, error)

	// (POST /practices)
	CreatePractice(ctx context.Context, request CreatePracticeRequestObject) (CreatePracticeResponseObject, error)

	// (GET /practices/{id})
	GetPractice(ctx context.Context, request GetPracticeRequestObject) (GetPracticeResponseObject, error)

	// (PATCH /practices/{id}/exercises/{exerciseId})
	SubmitExercise(ctx context.Context, request SubmitExerciseRequestObject) (SubmitExerciseResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ArchiveConcept operation middleware
func (sh *strictHandler) ArchiveConcept(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request ArchiveConceptRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ArchiveConcept(ctx, request.(ArchiveConceptRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ArchiveConcept")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ArchiveConceptResponseObject); ok {
		if err := validResponse.VisitArchiveConceptResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RestoreConcept operation middleware
func (sh *strictHandler) RestoreConcept(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request RestoreConceptRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RestoreConcept(ctx, request.(RestoreConceptRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RestoreConcept")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RestoreConceptResponseObject); ok {
		if err := validResponse.VisitRestoreConceptResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListNotes operation middleware
func (sh *strictHandler) ListNotes(w http.ResponseWriter, r *http.Request, params ListNotesParams) {
	var request ListNotesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListNotes(ctx, request.(ListNotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListNotes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListNotesResponseObject); ok {
		if err := validResponse.VisitListNotesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateNote operation middleware
func (sh *strictHandler) CreateNote(w http.ResponseWriter, r *http.Request) {
	var request CreateNoteRequestObject

	var body CreateNoteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateNote(ctx, request.(CreateNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateNote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateNoteResponseObject); ok {
		if err := validResponse.VisitCreateNoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteNote operation middleware
func (sh *strictHandler) DeleteNote(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteNoteRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteNote(ctx, request.(DeleteNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteNote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteNoteResponseObject); ok {
		if err := validResponse.VisitDeleteNoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNote operation middleware
func (sh *strictHandler) GetNote(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetNoteRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNote(ctx, request.(GetNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNoteResponseObject); ok {
		if err := validResponse.VisitGetNoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateNote operation middleware
func (sh *strictHandler) UpdateNote(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateNoteRequestObject

	request.Id = id

	var body UpdateNoteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateNote(ctx, request.(UpdateNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateNote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateNoteResponseObject); ok {
		if err := validResponse.VisitUpdateNoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPractices operation middleware
func (sh *strictHandler) ListPractices(w http.ResponseWriter, r *http.Request, params ListPracticesParams) {
	var request ListPracticesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPractices(ctx, request.(ListPracticesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPractices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPracticesResponseObject); ok {
		if err := validResponse.VisitListPracticesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePractice operation middleware
func (sh *strictHandler) CreatePractice(w http.ResponseWriter, r *http.Request) {
	var request CreatePracticeRequestObject

	var body CreatePracticeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePractice(ctx, request.(CreatePracticeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePractice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePracticeResponseObject); ok {
		if err := validResponse.VisitCreatePracticeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPractice operation middleware
func (sh *strictHandler) GetPractice(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetPracticeRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPractice(ctx, request.(GetPracticeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPractice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPracticeResponseObject); ok {
		if err := validResponse.VisitGetPracticeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitExercise operation middleware
func (sh *strictHandler) SubmitExercise(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, exerciseId openapi_types.UUID) {
	var request SubmitExerciseRequestObject

	request.Id = id
	request.ExerciseId = exerciseId

	var body SubmitExerciseJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitExercise(ctx, request.(SubmitExerciseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitExercise")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitExerciseResponseObject); ok {
		if err := validResponse.VisitSubmitExerciseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FrNcts2EH4VDtojY8lJLtXNSX/GU9tJ3Mkpo8nA5EpGSgI0sEysaDjTh+gT9kk6C/6LIEXLkuz2JonA",
	"Yvfbvw9LrVmg4kRJkGjYbM00mERJA/bLGx5ew10KBulbCCbQIkGhJJuxc/mVRyL0dL7Au1HhimU+e6vk",
	"IhKB3REoiSDtR54kkQg4bZ58MSRhzUxwCzGnTz9qWLAZ+2FSKzPJn5rJWw0c4b3mAYoArgv9WJZl/oZK",
	"5dHeP3/97XFPg1GpDsDjkQYerjy4FwYNKXml8FeVyrBr1pVCb2EfZT77KHmKt0qL79CzlJ6DRLIMQkYq",
	"FWrT8lzzK4XQQDHRKgGNIke4gRCuEmAzZlALuaTTUWAE9CQW8gLkEm/Z7NTfXJf5jFwgNKn4qdjkV4Ln",
	"1QZ18wUCtC7aQLRHN6kQzq3dC6VjjmzG0lSEbJsKxb4xJxe+7BwtdjhWuI/85R50IPJDQkH+i4XkqLRF",
	"licJyaKPaYTixV0qvvcF4iWt+JCK75XIzC/1Xl3xmM61x2c+UxLeLdjs03BoOyTOM59dCIMUNWYAIIS4",
	"/WHoHBJmIyoHh2vNba5GIhbN2BMSYQna2sWX4H6CCnnkerTpD6tZub6QWJ7p8hSZXYbG3kwvBbrM380S",
	"p+pqKWRvIiXcmG9Kh84sTw1oaYNnvSXAq5V+LdGlzOVAYu1wmvOITuDulsI+s5AJJcd7tDr7Q7HV6Vr7",
	"fc1ApjFZ08ju+YhCUixpqjcKhmswaeQs81pD0Ey1G6Ui4LIJwfk4xAxEECCE75IHbHoMHhtQnNMBHSX8",
	"ysZBoCqf7RovKulGy06CEO5xexbke2mpy6zNqLtrWNf1W3oTC2OKxzKNIn5D/R11Cv5D4uWpAuBBPnfh",
	"WMFTu3EwWP5oIdZG6H+RNC7rba8e4okdEgqWe3tCepdc/xmqb9IrTHPYFFgGFn7m2IIg5AgvUNjm0tkz",
	"NqNKvtrtcUn4wEOdabhBbVvGtA5x4VoRAQe2cRIBQnjWr95muvbhevYAWKFoGuNbX5N4btaekU4aTep9",
	"ZpBjapoJkIAM6aHPhPycaLXUYIz1SIHgyOZaKFEd0cSiCaXLj7YoYN1w6+vpfsh9o+jsjd43Zc4dNtRs",
	"bc83lIKP7P2eUsolYz7avDv8LXezwVDMy4WyQnMZ7HeluXf2/pz57CvovHGw05PpyTSnDiB5ItiMvTqZ",
	"nryyNBpvrYITusdPImLxVnuVW0E28LJh5CSf5eEMBt+ocLW3IUfrApG1k4Yqjv2hMZl5OZ12e8GFWi4h",
	"pEZg0iAAYxZpFNni8Hp62qdBJXbSmnZYxPnSUM7Sz2xOv1Q4qRQHgaLnHZVf96qsUtzQeeD4/PayBMfJ",
	"vwFeAnNjtRc/XQ4PoFKtQWK0as+FPLpL7dUNgZIBJGgmaxFmE66DW/EV+h1yli94m++yga95DAja2Nyn",
	"qLfJQLU5LxC2Trdj0G9gtG00Mx/j/EIfr9A/3BEi2vR6+6Zq5tfEtATSiasGg0oP4HqdL3iuuBb6PwNc",
	"qeGb3qyt5l09CN6loFc1hMUgqQYthAW31+5Tn7qIiImt1D2kMdZxC8xHUk6JL6c+i/l9IXI63XLA/ICl",
	"pzsVdFSg93xJ3AFCLxIGPbXwZDH7e1ztyR1I7d6dCfWo+0ANsjtLH9UlT/emQD5D7SJuL2AFZc1xnm7H",
	"ufFiZW+uqfLMFq88iomUd531s/29cNbzKFkWxVzfpyhXdXj30YqnQ2t6nBCuXno9GfQJx+C2C359vzga",
	"/vsvX91L0niSf3jfF6OT45WvfQQM1bukfF00yC2ql0rj+EU9nRgdNf6awX0SqRDYbMEjA75TcjXuqCVX",
	"c5/HzFi60yCDK3sjJsXZ4XmPv2+mdmgi1X3P6MiNi4JC1VH26GZdi9rGpap55SH51OZ/AI7Mqcb/taNc",
	"4/GA7hXHrlU/bd9U/e+lz92telVxtD6+0XD/f5pz1O/fB5z6VNxj2D2Taig9WZcfz3Ov9VCV9lz3GK7z",
	"nUJrbZ8jF3JP8I/Mh3pG8I4oLdd49gUuPm+eVBWrtg3la/fqr3Bcmm+gB5pTlmX/BgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
