// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Concept struct {
	ID             pgtype.UUID
	NoteID         pgtype.UUID
	Title          string
	Content        string
	Stability      pgtype.Numeric
	Difficulty     pgtype.Numeric
	DueAt          pgtype.Timestamptz
	LastReviewedAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	ArchivedAt     pgtype.Timestamptz
	ArchivedReason pgtype.Text
}

type Note struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	Content   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Practice struct {
	ID          pgtype.UUID
	NoteID      pgtype.UUID
	Status      string
	Exercises   json.RawMessage
	CreatedAt   pgtype.Timestamp
	CompletedAt pgtype.Timestamp
}

type User struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
